server:
  port: 8080
  #路径名
  servlet:
    context-path: /duike
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0 # 0-15db
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000
    # Jedis的配置,可以不配置,有默认值（RedisProperties类中有指定默认值）
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: -1
  application:
    name: duike

beetlsql:
  sqlPath: /sql
  basePackage: com.zile.beetlsql.mapper


#是否忽略token验证:true/false
isIgnoreToken: false